export default {
    GET_NOTIFICATIONS: 'GET_NOTIFICATIONS',
    MARK_NOTIFICATION_AS_READ_BY_ID: 'MARK_NOTIFICATION_AS_READ_BY_ID',
    MARK_ALL_NOTIFICATIONS: 'MARK_ALL_NOTIFICATIONS',
    START_NOTIFICATION_LOADING: 'START_NOTIFICATION_LOADING',
    END_NOTIFICATION_LOADING: 'END_NOTIFICATION_LOADING',

    START_SIGN_IN: 'START_SIGN_IN',
    SIGN_IN_SUCCESS : 'SIGN_IN_SUCCESS',
    SIGN_IN_FAIL: 'SIGN_IN_FAIL',
    SIGN_OUT: 'SIGN_OUT'
}