export default {
    MARK_NOTIFICATION_AS_READ_BY_ID: 'MARK_NOTIFICATION_AS_READ_BY_ID',
    MARK_ALL_NOTIFICATIONS: 'MARK_ALL_NOTIFICATIONS',
    START_NOTIFICATION_LOADING: 'START_NOTIFICATION_LOADING',
    END_NOTIFICATION_LOADING: 'END_NOTIFICATION_LOADING'
}